CollectionMonitoringSystem/Controllers/ReasonController.cs
using CollectionMonitoringSystem.Context;
using CollectionMonitoringSystem.Context.Models;
using CollectionMonitoringSystem.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CollectionMonitoringSystem.Controllers
{
    public class ReasonController : Controller
    {
        private IDataService<Reason, ReasonModel> reasonService = new ReasonService();
        private IDataService<ReasonStatus, ReasonStatusModel> reasonStatusService = new ReasonStatusService();
        ErrorLogService errorService = new ErrorLogService();
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Data(int? Id)
        {
            if (Id == null) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";

            ViewBag.StatusList = await reasonStatusService.GetEntityList();

            Reason entity = (await reasonService.GetEntity(Id ?? 0)) ?? new Reason();
            ReasonModel model = AutoMapper.Mapper.Map<ReasonModel>(entity);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Data(ReasonModel model)
        {
            if(ModelState.IsValid)
            {
                Reason entity = AutoMapper.Mapper.Map<Reason>(model);
                int notif = -1;
                if(model.Id == 0)
                {
                    int insert = await reasonService.InsertEntity(entity);
                    notif = insert > 0 ? 0 : -1;
                }
                else
                {
                    int update = await reasonService.UpdateEntity(entity);
                    notif = update > 0 ? 1 : -1;
                }
                TempData["notification"] = notif;
                return RedirectToAction("Index");
            }
            if(model.Id == 0) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";
            ViewBag.StatusList = await reasonStatusService.GetEntityList();
            return View(model);
        }

        [HttpGet]
        public async Task<JsonResult> GetReasonList()
        {
            return Json(new { data = await reasonService.GetEntityListJson() }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<int> DeleteReason(int id)
        {
            return await reasonService.DeleteEntity(id);
        }

        protected override void Dispose(bool disposing)
        {
            reasonService.Dispose();
            reasonStatusService.Dispose();
            base.Dispose(disposing);
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            base.OnException(filterContext);
            filterContext.ExceptionHandled = true;
            int result = errorService.LogError(filterContext.Exception);
            filterContext.Result = RedirectToAction("Index", "Error");
        }
    }
}

CollectionMonitoringSystem/Controllers/ReasonStatusController.cs
using CollectionMonitoringSystem.Context;
using CollectionMonitoringSystem.Context.Models;
using CollectionMonitoringSystem.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CollectionMonitoringSystem.Controllers
{
    public class ReasonStatusController : Controller
    {
        private IDataService<ReasonStatus, ReasonStatusModel> reasonStatusService = new ReasonStatusService();
        ErrorLogService errorService = new ErrorLogService();

        // GET: ReasonStatus
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Data(int? Id)
        {
            if (Id == null) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";

            ReasonStatus entity = (await reasonStatusService.GetEntity(Id ?? 0)) ?? new ReasonStatus();
            ReasonStatusModel model = AutoMapper.Mapper.Map<ReasonStatusModel>(entity);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Data(ReasonStatusModel model)
        {
            if (ModelState.IsValid)
            {
                ReasonStatus entity = AutoMapper.Mapper.Map<ReasonStatus>(model);
                int notif = -1;
                if (model.Id == 0)
                {
                    int insert = await reasonStatusService.InsertEntity(entity);
                    notif = insert > 0 ? 0 : -1;
                }
                else
                {
                    int update = await reasonStatusService.UpdateEntity(entity);
                    notif = update > 0 ? 1 : -1;
                }
                TempData["notification"] = notif;
                return RedirectToAction("Index");
            }
            if (model.Id == 0) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";
            return View(model);
        }

        [HttpGet]
        public async Task<JsonResult> GetReasonStatusList()
        {
            return Json(new { data = await reasonStatusService.GetEntityListJson() }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<int> DeleteReasonStatus(int id)
        {
            return await reasonStatusService.DeleteEntity(id);
        }

        protected override void Dispose(bool disposing)
        {
            reasonStatusService.Dispose();
            base.Dispose(disposing);
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            base.OnException(filterContext);
            filterContext.ExceptionHandled = true;
            int result = errorService.LogError(filterContext.Exception);
            filterContext.Result = RedirectToAction("Index", "Error");
        }
    }
}

CollectionMonitoringSystem/Views/Reason/Data.cshtml
@using CollectionMonitoringSystem.Context;
@using CollectionMonitoringSystem.Context.Models;
@using System.Collections.Generic;
@model ReasonModel
@{
    ViewBag.Title = ViewBag.SubTitle + " Reason";
}
<div class="row wrapper breadbox white-bg page-heading">
    <div class="col-lg-10">
        <h2>@ViewBag.SubTitle Reason</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Reason")">Reason</a>
            </li>
            <li>
                <a href="#">@ViewBag.SubTitle</a>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Reason @ViewBag.SubTitle Form</h5>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("Data", "Reason", FormMethod.Post))
                    {
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true)
                            <div class="form-group">
                                <label class="col-md-2 control-label">Description</label>
                                <div class="col-md-10">
                                    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label">Status</label>
                                <div class="col-md-10">
                                    @Html.DropDownListFor(x => x.StatusId, new SelectList((IList<ReasonStatus>)ViewBag.StatusList, "Id", "Description"), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.StatusId)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

CollectionMonitoringSystem/Views/Reason/Index.cshtml
@{
    ViewData["Title"] = "Reason List";
}

<div class="row wrapper breadbox white-bg page-heading">
    <div class="col-lg-10">
        <h2>Reason</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Reason")">Reason</a>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Reason List</h5>
                </div>
                <div class="ibox-content">
                    <span class="label label-add"><a href="@Url.Action("Data", "Reason")" style="color:#FFF;">Add Reason</a></span> <span class="label label-manage"><a href="@Url.Action("Index", "ReasonStatus")" style="color: #FFF;">Manage Status</a></span><br /><br />
                    <table class="table table-striped table-bordered table-condensed table-hover dataTables-config-list">
                        <thead>
                        <tr>
                            <th class="col-sm-2">Action</th>
                            <th class="col-sm-8">Reason</th>
                            <th class="col-sm-2">Status</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/dataTables/datatables.min.css" />
        <link rel="stylesheet" href="~/lib/dataTables/extensions/Scroller/css/scroller.dataTables.min.css" />  
    </environment>
}
@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/lib/dataTables/datatables.min.js"></script>
        <script src="~/lib/dataTables/extensions/Scroller/js/dataTables.scroller.min.js"></script>        
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.dataTables-config-list').DataTable({
                "dom": 'lTftp',
                "ajax": '@Url.Action("GetReasonList", "Reason")',
                "columns": [
                    {
                        "data": "Id", "render": function (data, type, row) {
                            return '<span class="label label-edit"><a href="@Url.Action("Data", "Reason")/' + data + '" style="color:#FFF;">Edit</a></span> ' +
                                   '<span class="label label-delete"><a href="javascript:deleteData(' + data + ');" style="color:#FFF;">Delete</a></span>';
                        }
                    },
                    { "data": "Description" },
                    { "data": "StatusDescription" }
                ]
            });
            @if((TempData["notification"] as int?) == 0)
            {
                @:toastr.success('A new data has been saved');
            }
            @if((TempData["notification"] as int?) == 1)
            {
                @:toastr.success('Data has been updated');
            }
        });

        function deleteData(id)
        {
            $.post("@Url.Action("DeleteReason", "Reason")", { id: id }, function (data) {
                if (data == 1)
                {
                    $('.dataTables-config-list').DataTable().ajax.reload();
                    toastr.warning('Data has been deleted');
                }
                else if(data == 2)
                {
                    toastr.error('Data can not be deleted because it is being used as a reference in another data', 'Foreign key constraint violation');
                }
                else
                {
                    toastr.error('Failed to delete data');
                }
            });
        }
    </script>
}