CollectionMonitoringSystem/Controllers/EmailController.cs
using CollectionMonitoringSystem.Context;
using CollectionMonitoringSystem.Context.Models;
using CollectionMonitoringSystem.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CollectionMonitoringSystem.Controllers
{
    public class EmailController : Controller
    {
        private IDataService<EmailNotification, EmailNotificationModel> emailService = new EmailService();
        private IDataService<EmailNotificationBeforeDue, EmailNotificationBeforeDueModel> emailBeforeDueService = new EmailBeforeDueService();
        private IDataService<EmailContent, EmailContentModel> emailContentService = new EmailContentService();
        ErrorLogService errorService = new ErrorLogService();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult BeforeDue()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetConfigurationList()
        {
            return Json(new { data = await emailService.GetEntityListJson() }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<JsonResult> GetConfigurationBeforeDueList()
        {
            return Json(new { data = await emailBeforeDueService.GetEntityListJson() }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Template()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetTemplateList()
        {
            return Json(new { data = await emailContentService.GetEntityListJson() }, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Data(int? Id)
        {
            if (Id == null) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";

            ViewBag.TemplateList = await emailContentService.GetEntityList();

            EmailNotification entity = (await emailService.GetEntity(Id ?? 0)) ?? new EmailNotification();
            EmailNotificationModel model = AutoMapper.Mapper.Map<EmailNotificationModel>(entity);

            return View(model);
        }        

        [HttpPost]
        public async Task<ActionResult> Data(EmailNotificationModel model)
        {
            if (ModelState.IsValid)
            {
                EmailNotification entity = AutoMapper.Mapper.Map<EmailNotification>(model);
                int notif = -1;
                if (model.Id == 0)
                {
                    int insert = await emailService.InsertEntity(entity);
                    notif = insert > 0 ? 0 : -1;
                }
                else
                {
                    int update = await emailService.UpdateEntity(entity);
                    notif = update > 0 ? 1 : -1;
                }
                TempData["notification"] = notif;
                return RedirectToAction("Index");
            }
            if (model.Id == 0) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";
            ViewBag.TemplateList = await emailContentService.GetEntityList();
            return View(model);
        }

        public async Task<ActionResult> DataBeforeDue(int? Id)
        {
            if (Id == null) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";

            ViewBag.TemplateList = await emailContentService.GetEntityList();

            EmailNotificationBeforeDue entity = (await emailBeforeDueService.GetEntity(Id ?? 0)) ?? new EmailNotificationBeforeDue();
            EmailNotificationBeforeDueModel model = AutoMapper.Mapper.Map<EmailNotificationBeforeDueModel>(entity);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> DataBeforeDue(EmailNotificationBeforeDueModel model)
        {
            if (ModelState.IsValid)
            {
                EmailNotificationBeforeDue entity = AutoMapper.Mapper.Map<EmailNotificationBeforeDue>(model);
                int notif = -1;
                if (model.Id == 0)
                {
                    int insert = await emailBeforeDueService.InsertEntity(entity);
                    notif = insert > 0 ? 0 : -1;
                }
                else
                {
                    int update = await emailBeforeDueService.UpdateEntity(entity);
                    notif = update > 0 ? 1 : -1;
                }
                TempData["notification"] = notif;
                return RedirectToAction("BeforeDue");
            }
            if (model.Id == 0) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";
            ViewBag.TemplateList = await emailContentService.GetEntityList();
            return View(model);
        }

        public async Task<ActionResult> TemplateData(int? Id)
        {
            if (Id == null) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";

            EmailContent entity = (await emailContentService.GetEntity(Id ?? 0)) ?? new EmailContent();
            EmailContentModel model = AutoMapper.Mapper.Map<EmailContentModel>(entity);

            return View(model);
        }

        [HttpPost, ValidateInput(false)]
        public async Task<ActionResult> TemplateData(EmailContentModel model)
        {
            if (ModelState.IsValid)
            {
                EmailContent entity = AutoMapper.Mapper.Map<EmailContent>(model);
                int notif = -1;
                if (model.Id == 0)
                {
                    int insert = await emailContentService.InsertEntity(entity);
                    notif = insert > 0 ? 0 : -1;
                }
                else
                {
                    int update = await emailContentService.UpdateEntity(entity);
                    notif = update > 0 ? 1 : -1;
                }
                TempData["notification"] = notif;
                return RedirectToAction("Template");
            }
            if (model.Id == 0) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";
            return View(model);
        }

        [HttpPost]
        public async Task<int> DeleteTemplate(int id)
        {
            return await emailContentService.DeleteEntity(id);
        }

        [HttpPost]
        public async Task<int> DeleteEmailConfiguration(int id)
        {
            return await emailService.DeleteEntity(id);
        }

        [HttpPost]
        public async Task<int> DeleteEmailBeforeDueConfiguration(int id)
        {
            return await emailBeforeDueService.DeleteEntity(id);
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            base.OnException(filterContext);
            filterContext.ExceptionHandled = true;
            int result = errorService.LogError(filterContext.Exception);
            filterContext.Result = RedirectToAction("Index", "Error");
        }
    }
}

CollectionMonitoringSystem/Controllers/FinanceController.cs
using CollectionMonitoringSystem.Context;
using CollectionMonitoringSystem.Context.Models;
using CollectionMonitoringSystem.Manager;
using CollectionMonitoringSystem.Models;
using CollectionMonitoringSystem.UserManagement;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CollectionMonitoringSystem.Controllers
{
    public class FinanceController : Controller
    {
        private FinanceService financeService = new FinanceService();
        private ErrorLogService errorService = new ErrorLogService();

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Data(int? Id)
        {
            if (Id == null) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";

            FinanceDataModel model = new Models.FinanceDataModel();

            Finance entity = (await financeService.GetEntity(Id ?? 0)) ?? new Finance();
            FinanceModel fModel = AutoMapper.Mapper.Map<FinanceModel>(entity);

            model.FinanceModel = fModel;
            model.EmployeeMasters = new UserManagementContext().GetEmployeeList();

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Data(FinanceDataModel model)
        {
            if (ModelState.IsValid)
            {
                Finance entity = AutoMapper.Mapper.Map<Finance>(model.FinanceModel);
                int notif = -1;
                if (model.FinanceModel.Id == 0)
                {
                    int insert = await financeService.InsertEntity(entity);
                    notif = insert > 0 ? 0 : -1;
                }
                else
                {
                    int update = await financeService.UpdateEntity(entity);
                    notif = update > 0 ? 1 : -1;
                }
                TempData["notification"] = notif;
                return RedirectToAction("Index");
            }
            if (model.FinanceModel.Id == 0) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";

            model.EmployeeMasters = new UserManagementContext().GetEmployeeList();
            return View(model);
        }

        [HttpGet]
        public JsonResult GetEmployeeEmail(string xupj)
        {
            string empId = new UserManagementContext().GetEmployeeList().FirstOrDefault(x => x.Xupj == xupj)?.EmployeeId?.ToString() ?? "XXX";
            string email = new UserManagementContext().GetEmployeeEmail(empId);

            if (!string.IsNullOrEmpty(email))
                return Json(email, JsonRequestBehavior.AllowGet);
            else
                return Json(new Helpers.LoginHelpers().GetUserProfileEmailById(xupj).Trim(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetEmployeePosition(string xupj)
        {
            return Json(new UserManagementContext().GetEmployeeList().FirstOrDefault(x => x.Xupj == xupj)?.PositionName ?? "", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<JsonResult> GetFinanceList()
        {
            return Json(new { data = await financeService.GetEntityListJson() }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<int> DeleteFinance(int id)
        {
            return await financeService.DeleteEntity(id);
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            base.OnException(filterContext);
            filterContext.ExceptionHandled = true;
            int result = errorService.LogError(filterContext.Exception);
            filterContext.Result = RedirectToAction("Index", "Error");
        }
    }
}

CollectionMonitoringSystem/Views/Finance/Data.cshtml
@using CollectionMonitoringSystem.Context;
@using CollectionMonitoringSystem.Models;
@using CollectionMonitoringSystem.Context.Models;
@using System.Collections.Generic;
@model FinanceDataModel
@{
    ViewBag.Title = ViewBag.SubTitle + " Employee Data";
}
<div class="row wrapper breadbox white-bg page-heading">
    <div class="col-lg-10">
        <h2>@ViewBag.SubTitle Employee</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Email")">Email Configuration</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Finance")">Employee</a>
            </li>
            <li>
                <a href="#">@ViewBag.SubTitle</a>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Employee @ViewBag.SubTitle Form</h5>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("Data", "Finance", FormMethod.Post))
                    {
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true)
                            <div class="form-group required">
                                <label class="col-md-2 control-label">Business Area</label>
                                <div class="col-md-10">
                                    @Html.TextBoxFor(x => x.FinanceModel.BusinessArea, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.FinanceModel.BusinessArea, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group required">
                                <label class="col-md-2 control-label">Employee Name</label>
                                <div class="col-md-10 ">
                                    <select id="cmbName" class="chosenName form-control">
                                        <option></option>
                                        @foreach(var x in Model.EmployeeMasters)
                                        {
                                            <option value="@x.Xupj">@x.EmployeeName</option>
                                        }
                                    </select><br />
                                    @Html.TextBoxFor(x => x.FinanceModel.Name, new { @class = "form-control", style = "display: none;" })
                                    @Html.ValidationMessageFor(x => x.FinanceModel.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group required">
                                <label class="col-md-2 control-label">Position Type</label>
                                <div class="col-md-10 ">
                                    @Html.EnumDropDownListFor(x => x.FinanceModel.PositionType, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.FinanceModel.PositionType, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group required">
                                <label class="col-md-2 control-label">Position Name</label>
                                <div class="col-md-10 ">
                                    @Html.TextBoxFor(x => x.FinanceModel.PositionName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.FinanceModel.PositionName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group required">
                                <label class="col-md-2 control-label">Email</label>
                                <div class="col-md-10 ">
                                    @Html.TextBoxFor(x => x.FinanceModel.Email, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.FinanceModel.Email, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/dataTables/datatables.min.css" />
        <link rel="stylesheet" href="~/lib/dataTables/extensions/Scroller/css/scroller.dataTables.min.css" />
        <link rel="stylesheet" href="~/lib_bower/chosen_v1.7.0/chosen.min.css" />
    </environment>
}
@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/lib_bower/chosen_v1.7.0/chosen.jquery.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {
            $(".chosenName").chosen({
                 disable_search_threshold: 10,
                 no_results_text: "Oops, nothing found!",
                 width: "250"
             });
        });

        $('#cmbName').change(function () {
            $('#FinanceModel_Name').val($('#cmbName option:selected').text());
            LoadData($(this).val());
            LoadPosition($(this).val());
        });        

        function LoadData(val)
        {
            $.ajax({
                type: "GET",
                url: '@Url.Action("GetEmployeeEmail", "Finance")?xupj=' + val,
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                async: false,
                success: function (myJSONString) {
                    if (myJSONString.length == 0 || myJSONString.indexOf('Failed') !== -1)
                    {
                        toastr.error('Failed to retrive email via portal service. Please input email manually');
                        $('#FinanceModel_Email').val('');
                    }                        
                    else
                    {
                        $('#FinanceModel_Email').val(myJSONString);
                    }                        
                },
                error: function (response) {
                    toastr.error('Failed to retrive email via portal service. Please input email manually');
                    $('#FinanceModel_Email').val('');
                }
            });
        }

        function LoadPosition(val) {
            $.ajax({
                type: "GET",
                url: '@Url.Action("GetEmployeePosition", "Finance")?xupj=' + val,
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                async: false,
                success: function (myJSONString) {
                    if (myJSONString.length == 0)
                    {
                        toastr.error('Failed to retrive position name. Please input position name manually');
                        $('#FinanceModel_PositionName').val('');
                    }                        
                    else
                    {
                        $('#FinanceModel_PositionName').val(myJSONString);
                    }                       
                },
                error: function (response) {
                    toastr.error('Failed to retrive position name. Please input position name manually');
                    $('#FinanceModel_PositionName').val('');
                }
            });
        }
    </script>
}

CollectionMonitoringSystem/Views/Finance/Index.cshtml
@{
    ViewBag.Title = "Manage Email";
}

<div class="row wrapper breadbox white-bg page-heading">
    <div class="col-lg-10">
        <h2>Manage Email</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Email")">Email Configuration</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Finance")">Manage Email</a>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Employee Email List</h5>
                </div>
                <div class="ibox-content">
                    <span class="label label-add"><a href="@Url.Action("Data", "Finance")" style="color:#FFF;">Add Employee</a></span>
                    <br /><br />
                    <table class="table table-striped table-bordered table-condensed table-hover dataTables-config-list">
                        <thead>
                            <tr>
                                <th>Action </th>
                                <th>Business Area</th>
                                <th>Employee Name</th>
                                <th>Position Type</th>
                                <th>Position Name</th>
                                <th>Email</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/dataTables/datatables.min.css" />
        <link rel="stylesheet" href="~/lib/dataTables/extensions/Scroller/css/scroller.dataTables.min.css" />
        <link rel="stylesheet" href="~/lib_bower/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/lib_bower/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" />
    </environment>
}
@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/lib/dataTables/datatables.min.js"></script>
        <script src="~/lib/dataTables/extensions/Scroller/js/dataTables.scroller.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.dataTables-config-list').DataTable({
                "dom": 'lTftp',
                "ajax": '@Url.Action("GetFinanceList", "Finance")',
                "columns": [
                    {
                        "data": "Id", "render": function (data, type, row) {
                            return '<span class="label label-edit"><a href="@Url.Action("Data", "Finance")/' + data + '" style="color:#FFF;">Edit</a></span> ' +
                                   '<span class="label label-delete"><a href="javascript:deleteData(' + data + ');" style="color:#FFF;">Delete</a></span>';
                        }
                    },
                    { "data": "BusinessArea" },
                    { "data": "Name" },
                    { "data": "PositionTypeName" },
                    { "data": "PositionName" },
                    { "data": "Email" }
                ]
            });
            @if((TempData["notification"] as int?) == 0)
            {
                @:toastr.success('A new data has been saved');
            }
            @if((TempData["notification"] as int?) == 1)
            {
                @:toastr.success('Data has been updated');
            }
        });

        function deleteData(id) {
            $.post("@Url.Action("DeleteFinance", "Finance")", { id: id }, function (data) {
                if (data == 1) {
                    $('.dataTables-config-list').DataTable().ajax.reload();
                    toastr.warning('Data has been deleted');
                }
                else {
                    toastr.error('Failed to delete data');
                }
            });
        }
    </script>
}