CollectionMonitoringSystem/Controllers/CustomerMarketSectorController.cs
using CollectionMonitoringSystem.Context;
using CollectionMonitoringSystem.Context.Models;
using CollectionMonitoringSystem.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CollectionMonitoringSystem.Controllers
{
    public class CustomerMarketSectorController : Controller
    {
        private IDataService<MarketSector, MarketSectorModel> marketSectorService = new MarketSectorService();
        private CustomerMarketSectorService customerMarketSectorService = new CustomerMarketSectorService();
        ErrorLogService errorService = new ErrorLogService();
        // GET: CustomerMarketSector
        public ActionResult Index()
        {
            return View();
        }
        public async Task<ActionResult> Data(int? Id)
        {
            if (Id == null) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";

            ViewBag.SectorList = await marketSectorService.GetEntityList();

            CustomerMarketSector entity = (await customerMarketSectorService.GetEntity(Id ?? 0)) ?? new CustomerMarketSector();
            CustomerMarketSectorModel model = AutoMapper.Mapper.Map<CustomerMarketSectorModel>(entity);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Data(CustomerMarketSectorModel model)
        {
            if (ModelState.IsValid)
            {
                CustomerMarketSector entity = AutoMapper.Mapper.Map<CustomerMarketSector>(model);
                int notif = -1;
                if (model.Id == 0)
                {
                    int insert = await customerMarketSectorService.InsertEntity(entity);
                    notif = insert > 0 ? 0 : -1;
                }
                else
                {
                    int update = await customerMarketSectorService.UpdateEntity(entity);
                    notif = update > 0 ? 1 : -1;
                }
                TempData["notification"] = notif;
                return RedirectToAction("Index");
            }
            if (model.Id == 0) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";
            ViewBag.SectorList = await marketSectorService.GetEntityList();
            return View(model);
        }

        [HttpGet]
        public async Task<JsonResult> GetCustomerList(int draw, int start, int length)
        {
            string search = Request.QueryString["search[value]"];
            var dataList = await customerMarketSectorService.GetEntityListJson(search);
            var totalRow = dataList.Count;

            return Json(new { draw = draw, recordsTotal = totalRow, recordsFiltered = totalRow, data = dataList.GetRange(start, Math.Min(length, totalRow - start)) }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<int> DeleteCustomer(int id)
        {
            return await customerMarketSectorService.DeleteEntity(id);
        }

        protected override void Dispose(bool disposing)
        {
            customerMarketSectorService.Dispose();
            marketSectorService.Dispose();
            base.Dispose(disposing);
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            base.OnException(filterContext);
            filterContext.ExceptionHandled = true;
            int result = errorService.LogError(filterContext.Exception);
            filterContext.Result = RedirectToAction("Index", "Error");
        }
    }
}

CollectionMonitoringSystem/Controllers/MarketSectorController.cs
using CollectionMonitoringSystem.Context;
using CollectionMonitoringSystem.Context.Models;
using CollectionMonitoringSystem.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CollectionMonitoringSystem.Controllers
{
    public class MarketSectorController : Controller
    {
        private IDataService<MarketSector, MarketSectorModel> marketSectorService = new MarketSectorService();
        ErrorLogService errorService = new ErrorLogService();

        // GET: MarketSector
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Data(int? Id)
        {
            if (Id == null) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";

            MarketSector entity = (await marketSectorService.GetEntity(Id ?? 0)) ?? new MarketSector();
            MarketSectorModel model = AutoMapper.Mapper.Map<MarketSectorModel>(entity);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Data(MarketSectorModel model)
        {
            if (ModelState.IsValid)
            {
                MarketSector entity = AutoMapper.Mapper.Map<MarketSector>(model);
                int notif = -1;
                if (model.Id == 0)
                {
                    int insert = await marketSectorService.InsertEntity(entity);
                    notif = insert > 0 ? 0 : -1;
                }
                else
                {
                    int update = await marketSectorService.UpdateEntity(entity);
                    notif = update > 0 ? 1 : -1;
                }
                TempData["notification"] = notif;
                return RedirectToAction("Index");
            }
            if (model.Id == 0) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";
            return View(model);
        }

        [HttpGet]
        public async Task<JsonResult> GetMarketSectorList()
        {
            return Json(new { data = await marketSectorService.GetEntityListJson() }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<int> DeleteMarketSector(int id)
        {
            return await marketSectorService.DeleteEntity(id);
        }

        protected override void Dispose(bool disposing)
        {
            marketSectorService.Dispose();
            base.Dispose(disposing);
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            base.OnException(filterContext);
            filterContext.ExceptionHandled = true;
            int result = errorService.LogError(filterContext.Exception);
            filterContext.Result = RedirectToAction("Index", "Error");
        }
    }
}

CollectionMonitoringSystem/Views/MarketSector/Data.cshtml
@using CollectionMonitoringSystem.Context.Models;
@model MarketSectorModel
@{
    ViewBag.Title = ViewBag.SubTitle + " Market Sector";
}
<div class="row wrapper breadbox white-bg page-heading">
    <div class="col-lg-10">
        <h2>@ViewBag.SubTitle Market Sector</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "CustomerMarketSector")">Customer</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "MarketSector")">Market Sector</a>
            </li>
            <li>
                <a href="#">@ViewBag.SubTitle</a>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Market Sector @ViewBag.SubTitle Form</h5>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("Data", "MarketSector", FormMethod.Post))
                    {
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true)
                            <div class="form-group required">
                                <label class="col-md-2 control-label">Description</label>
                                <div class="col-md-10">
                                    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

CollectionMonitoringSystem/Views/MarketSector/Index.cshtml
@{
    ViewData["Title"] = "Market Sector List";
}
<div class="row wrapper breadbox white-bg page-heading">
    <div class="col-lg-10">
        <h2>Market Sector</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "CustomerMarketSector")">Customer</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "MarketSector")">Market Sector</a>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Market Sector List</h5>
                </div>
                <div class="ibox-content">
                    <span class="label label-add"><a href="@Url.Action("Data", "MarketSector")" style="color:#FFF;">Add Market Sector</a></span><br/><br/>
                    <table class="table table-striped table-bordered table-condensed table-hover dataTables-config-list">
                        <thead>
                        <tr>
                            <th>Action</th>
                            <th class="col-sm-10">Description</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/dataTables/datatables.min.css" />
        <link rel="stylesheet" href="~/lib/dataTables/extensions/Scroller/css/scroller.dataTables.min.css" />
    </environment>
}
@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/lib/dataTables/datatables.min.js"></script>
        <script src="~/lib/dataTables/extensions/Scroller/js/dataTables.scroller.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.dataTables-config-list').DataTable({
                "dom": 'lTftp',
                "ajax": '@Url.Action("GetMarketSectorList", "MarketSector")',
                "columns": [
                    {
                        "data": "Id", "render": function (data, type, row) {
                            return '<span class="label label-edit"><a href="@Url.Action("Data", "MarketSector")/' + data + '" style="color:#FFF;">Edit</a></span> ' +
                                   '<span class="label label-delete"><a href="javascript:deleteData(' + data + ');" style="color:#FFF;">Delete</a></span>';
                        }
                    },
                    { "data": "Description" }
                ]
            });
            @if((TempData["notification"] as int?) == 0)
            {
                @:toastr.success('A new data has been saved');
            }
            @if((TempData["notification"] as int?) == 1)
            {
                @:toastr.success('Data has been updated');
            }
        });

        function deleteData(id) {
            $.post("@Url.Action("DeleteMarketSector", "MarketSector")", { id: id }, function (data) {
                if (data == 1) {
                    $('.dataTables-config-list').DataTable().ajax.reload();
                    toastr.warning('Data has been deleted');
                }
                else if (data == 2) {
                    toastr.error('Data can not be deleted because it is being used as a reference in another data', 'Foreign key constraint violation');
                }
                else {
                    toastr.error('Failed to delete data');
                }
            });
        }
    </script>
}