CollectionMonitoringSystem/Controllers/ClassificationController.cs
using CollectionMonitoringSystem.Context;
using CollectionMonitoringSystem.Context.Models;
using CollectionMonitoringSystem.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CollectionMonitoringSystem.Controllers
{
    public class ClassificationController : Controller
    {
        private IDataService<Classification, ClassificationModel> classificationService = new ClassificationService();
        ErrorLogService errorService = new ErrorLogService();

        // GET: Classification
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Data(int? Id)
        {
            if (Id == null) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";

            Classification entity = (await classificationService.GetEntity(Id ?? 0)) ?? new Classification();
            ClassificationModel model = AutoMapper.Mapper.Map<ClassificationModel>(entity);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Data(ClassificationModel model)
        {
            if (ModelState.IsValid)
            {
                Classification entity = AutoMapper.Mapper.Map<Classification>(model);
                int notif = -1;
                if (model.Id == 0)
                {
                    int insert = await classificationService.InsertEntity(entity);
                    notif = insert > 0 ? 0 : -1;
                }
                else
                {
                    int update = await classificationService.UpdateEntity(entity);
                    notif = update > 0 ? 1 : -1;
                }
                TempData["notification"] = notif;
                return RedirectToAction("Index");
            }
            if (model.Id == 0) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";
            return View(model);
        }

        [HttpGet]
        public async Task<JsonResult> GetClassificationList()
        {
            return Json(new { data = await classificationService.GetEntityListJson() }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<int> DeleteClassification(int id)
        {
            return await classificationService.DeleteEntity(id);
        }

        protected override void Dispose(bool disposing)
        {
            classificationService.Dispose();
            base.Dispose(disposing);
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            base.OnException(filterContext);
            filterContext.ExceptionHandled = true;
            int result = errorService.LogError(filterContext.Exception);
            filterContext.Result = RedirectToAction("Index", "Error");
        }
    }
}

CollectionMonitoringSystem/Controllers/CustomerClassificationController.cs
using CollectionMonitoringSystem.Context;
using CollectionMonitoringSystem.Context.Models;
using CollectionMonitoringSystem.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CollectionMonitoringSystem.Controllers
{
    public class CustomerClassificationController : Controller
    {
        private IDataService<Classification, ClassificationModel> classificationService = new ClassificationService();
        private IDataService<CustomerClassification, CustomerClassificationModel> customerClassificationService = new CustomerClassificationService();
        ErrorLogService errorService = new ErrorLogService();
        // GET: CustomerClassification
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Data(int? Id)
        {
            if (Id == null) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";

            ViewBag.ClassificationList = await classificationService.GetEntityList();

            CustomerClassification entity = (await customerClassificationService.GetEntity(Id ?? 0)) ?? new CustomerClassification();
            CustomerClassificationModel model = AutoMapper.Mapper.Map<CustomerClassificationModel>(entity);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Data(CustomerClassificationModel model)
        {
            if (ModelState.IsValid)
            {
                CustomerClassification entity = AutoMapper.Mapper.Map<CustomerClassification>(model);
                int notif = -1;
                if (model.Id == 0)
                {
                    int insert = await customerClassificationService.InsertEntity(entity);
                    notif = insert > 0 ? 0 : -1;
                }
                else
                {
                    int update = await customerClassificationService.UpdateEntity(entity);
                    notif = update > 0 ? 1 : -1;
                }
                TempData["notification"] = notif;
                return RedirectToAction("Index");
            }
            if (model.Id == 0) ViewBag.SubTitle = "Add";
            else ViewBag.SubTitle = "Edit";
            ViewBag.ClassificationList = await classificationService.GetEntityList();
            return View(model);
        }

        [HttpGet]
        public async Task<JsonResult> GetCustomerList()
        {
            return Json(new { data = await customerClassificationService.GetEntityListJson() }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<int> DeleteCustomer(int id)
        {
            return await customerClassificationService.DeleteEntity(id);
        }

        protected override void Dispose(bool disposing)
        {
            customerClassificationService.Dispose();
            classificationService.Dispose();
            base.Dispose(disposing);
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            base.OnException(filterContext);
            filterContext.ExceptionHandled = true;
            int result = errorService.LogError(filterContext.Exception);
            filterContext.Result = RedirectToAction("Index", "Error");
        }
    }    
}

CollectionMonitoringSystem/Views/Classification/Data.cshtml
@using CollectionMonitoringSystem.Context.Models;
@model ClassificationModel
@{
    ViewBag.Title = ViewBag.SubTitle + " Classification";
}
<div class="row wrapper breadbox white-bg page-heading">
    <div class="col-lg-10">
        <h2>@ViewBag.SubTitle Classification</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "CustomerClassification")">Customer</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Classification")">Classification</a>
            </li>
            <li>
                <a href="#">@ViewBag.SubTitle</a>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Classification @ViewBag.SubTitle Form</h5>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("Data", "Classification", FormMethod.Post))
                    {
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true)
                            <div class="form-group required">
                                <label class="col-md-2 control-label">Description</label>
                                <div class="col-md-10">
                                    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

CollectionMonitoringSystem/Views/Classification/Index.cshtml
@{
    ViewData["Title"] = "Classification List";
}
<div class="row wrapper breadbox white-bg page-heading">
    <div class="col-lg-10">
        <h2>Classification</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "CustomerClassification")">Customer</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Classification")">Classification</a>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Classification List</h5>
                </div>
                <div class="ibox-content">
                    <span class="label label-add"><a href="@Url.Action("Data", "Classification")" style="padding-left:5px;padding-right:5px;color:#FFF;">Add Classification</a></span><br/><br/>
                    <table class="table table-striped table-bordered table-condensed table-hover dataTables-config-list">
                        <thead>
                        <tr>
                            <th>Action </th>
                            <th class="col-sm-10">Description</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/dataTables/datatables.min.css" />
        <link rel="stylesheet" href="~/lib/dataTables/extensions/Scroller/css/scroller.dataTables.min.css" />
    </environment>
}
@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/lib/dataTables/datatables.min.js"></script>
        <script src="~/lib/dataTables/extensions/Scroller/js/dataTables.scroller.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.dataTables-config-list').DataTable({
                "dom": 'lTftp',
                "ajax": '@Url.Action("GetClassificationList", "Classification")',
                "columns": [
                    {
                        "data": "Id", "render": function (data, type, row) {
                            return '<span class="label label-edit"><a href="@Url.Action("Data", "Classification")/' + data + '" style="color:#FFF;">Edit</a></span> ' +
                                   '<span class="label label-delete"><a href="javascript:deleteData(' + data + ');" style="color:#FFF;">Delete</a></span>';
                        }
                    },
                    { "data": "Description" }
                ]
            });
            @if((TempData["notification"] as int?) == 0)
            {
                @:toastr.success('A new data has been saved');
            }
            @if((TempData["notification"] as int?) == 1)
            {
                @:toastr.success('Data has been updated');
            }
        });

        function deleteData(id) {
            $.post("@Url.Action("DeleteClassification", "Classification")", { id: id }, function (data) {
                if (data == 1) {
                    $('.dataTables-config-list').DataTable().ajax.reload();
                    toastr.warning('Data has been deleted');
                }
                else if (data == 2) {
                    toastr.error('Data can not be deleted because it is being used as a reference in another data', 'Foreign key constraint violation');
                }
                else {
                    toastr.error('Failed to delete data');
                }
            });
        }
    </script>
}